# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM registry-public.lenovo.com/library/ubuntu:20.04 AS builder
ARG TARGETARCH
RUN apt-get update
RUN apt-get -y install ca-certificates g++ wget
RUN wget -qO- http://10.122.143.90/go1.24.6.linux-${TARGETARCH}.tar.gz | tar -C /usr/local -zx
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
WORKDIR /go/src/volcano.sh/devices
ENV GOPROXY="https://goproxy.cn,direct"

COPY . .
RUN go env -w GOARCH=${TARGETARCH}
RUN go env -w CGO_LDFLAGS_ALLOW='-Wl,--unresolved-symbols=ignore-in-object-files'
RUN go build -ldflags="-s -w" -o volcano-vgpu-device-plugin ./cmd/vgpu
RUN go build -ldflags="-s -w" -o volcano-vgpu-monitor ./cmd/vgpu-monitor
RUN go install github.com/NVIDIA/mig-parted/cmd/nvidia-mig-parted@latest
RUN wget -O /go/src/volcano.sh/devices/libvgpu/libvgpu.so https://registry-dev.xcloud.lenovo.com:18082/repository/binary-k8s-raw/libvgpu/2.6.0/${TARGETARCH}/libvgpu.so


FROM registry-public.lenovo.com/library/ubuntu:24.04

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=utility

COPY --from=builder /go/src/volcano.sh/devices/volcano-vgpu-device-plugin /usr/bin/volcano-vgpu-device-plugin
COPY --from=builder /go/src/volcano.sh/devices/volcano-vgpu-monitor /usr/bin/volcano-vgpu-monitor
COPY --from=builder /go/bin/nvidia-mig-parted /usr/bin/nvidia-mig-parted
COPY --from=builder /go/src/volcano.sh/devices/lib/nvidia/ld.so.preload /k8s-vgpu/lib/nvidia/
COPY --from=builder /go/src/volcano.sh/devices/libvgpu/libvgpu.so /k8s-vgpu/lib/nvidia/
RUN chmod 0755 /k8s-vgpu/lib/nvidia/libvgpu.so

ENTRYPOINT ["volcano-vgpu-device-plugin"]
